"""Rocky as an mjlab Entity: actuators, collisions and initial state."""

from __future__ import annotations

import math

import mujoco

from mjlab.actuator import BuiltinPositionActuatorCfg
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg
from mjlab.utils.actuator import ElectricActuator, reflected_inertia
from mjlab.utils.spec_config import CollisionCfg

from rocky import ROCKY_XML
from rocky import model_params as P
from rocky.gait import GaitParams, WaveGait

##
# MJCF.
##


def get_spec() -> mujoco.MjSpec:
    """Load the CAD-exported MJCF, stripped of its keyframe.

    model/rocky.xml ships a "home" keyframe holding the CAD standing pose, which
    is what you want when opening the model by hand. mjlab only ever uses an
    entity's *first* keyframe, so leaving it in place would silently override the
    initial state configured below -- the gait stance, which is what training
    should start from. Deleting it makes mjlab build the keyframe from
    `INIT_STATE` instead.
    """
    if not ROCKY_XML.exists():
        raise FileNotFoundError(
            f"Rocky MJCF not found at {ROCKY_XML}. It is generated by "
            "model/build_model.py from the Fusion export."
        )
    spec = mujoco.MjSpec.from_file(str(ROCKY_XML))
    while spec.keys:
        spec.delete(spec.keys[0])
    return spec


##
# Actuators: Feetech STS3215 at 12 V, one per joint.
##

STS3215 = ElectricActuator(
    reflected_inertia=reflected_inertia(P.ROTOR_INERTIA, P.GEAR_RATIO),
    velocity_limit=P.VELOCITY_LIMIT,
    effort_limit=P.EFFORT_LIMIT,
)

STIFFNESS = STS3215.reflected_inertia * P.NATURAL_FREQ**2
DAMPING = 2 * P.DAMPING_RATIO * STS3215.reflected_inertia * P.NATURAL_FREQ

ROCKY_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
    target_names_expr=(P.SWEEP_RE, P.LIFT_RE, P.ELBOW_RE, P.WRIST_RE),
    stiffness=STIFFNESS,
    damping=DAMPING,
    effort_limit=STS3215.effort_limit,
    armature=STS3215.reflected_inertia,
    frictionloss=P.FRICTIONLOSS,
)

# Action scale, in radians of setpoint offset per unit action.
#
# mjlab's heuristic (0.25 * effort / stiffness) gives 0.031 rad here: a 1.8 deg
# command envelope, which cannot produce a stride. That rule suits a
# quasi-direct-drive motor, not a 1:345 hobby servo whose torque is small
# relative to its reflected inertia. These are sized from the joint excursions
# the scripted gait actually uses (see docs/gait.md), with headroom.
ROCKY_ACTION_SCALE: dict[str, float] = {
    P.SWEEP_RE: 0.25,
    P.LIFT_RE: 0.40,
    P.ELBOW_RE: 0.40,
    P.WRIST_RE: 0.30,
}

##
# Initial state: the gait's neutral stance, not the CAD pose.
##

GAIT = WaveGait(GaitParams())

INIT_STATE = EntityCfg.InitialStateCfg(
    pos=(0.0, 0.0, GAIT.p.stance_height + 0.0005),
    joint_pos=GAIT.neutral_joint_dict(),
    joint_vel={".*": 0.0},
)

##
# Collisions.
##

_foot_regex = r"^foot_[0-4]_collision$"
_collision_regex = r".*_collision$"

FEET_ONLY_COLLISION = CollisionCfg(
    geom_names_expr=(_foot_regex,),
    contype=0,
    conaffinity=1,
    condim=3,
    priority=1,
    friction=(0.8,),
    solimp=(0.9, 0.95, 0.023),
)

# Per-link convex hulls collide as well, but frictionless (condim 1), so only the
# feet provide traction while shins and belly can still catch on terrain.
FULL_COLLISION = CollisionCfg(
    geom_names_expr=(_collision_regex,),
    contype=1,
    conaffinity=1,
    solref=(0.01, 1),
    condim={_foot_regex: 6, _collision_regex: 1},
    priority={_foot_regex: 1, ".*": 0},
    friction={_foot_regex: (1.0, 5e-3, 5e-4)},
)

##
# Entity.
##

ROCKY_ARTICULATION = EntityArticulationInfoCfg(
    actuators=(ROCKY_ACTUATOR_CFG,),
    soft_joint_pos_limit_factor=0.9,
)


def get_rocky_robot_cfg() -> EntityCfg:
    """A fresh Rocky EntityCfg (new instance per call, to avoid shared mutation)."""
    return EntityCfg(
        init_state=INIT_STATE,
        collisions=(FULL_COLLISION,),
        spec_fn=get_spec,
        articulation=ROCKY_ARTICULATION,
    )


if __name__ == "__main__":
    import mujoco.viewer as viewer

    from mjlab.entity.entity import Entity

    viewer.launch(Entity(get_rocky_robot_cfg()).spec.compile())
